{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0401fdfd-ade7-47d4-ab77-93be7c0c23bd",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "Answer 1:When creating a custom exception in a programming language, it is common practice to inherit from the base Exception class or its equivalent. Here are the reasons why using the Exception class is recommended:\n",
    "\n",
    "1 Consistency and Familiarity: By deriving from the Exception class, your custom exception becomes consistent with other built-in exceptions in the language. This consistency makes it easier for other developers to understand and handle your custom exception, as they are already familiar with the behaviors and conventions associated with the base Exception class.\n",
    "\n",
    "2 Exception Hierarchy: The base Exception class is typically at the top of the exception hierarchy in a programming language. This hierarchy allows for structured exception handling, where different types of exceptions can be caught and handled differently. By inheriting from Exception, your custom exception becomes part of this hierarchy and can be caught and processed along with other exceptions.\n",
    "\n",
    "3 Polymorphism and Code Reusability: Inheritance from Exception allows your custom exception to be treated as a general exception type. This means that wherever an Exception is expected, your custom exception can be used as a substitute. This polymorphic behavior enables code reusability, as you can write exception handling logic that can handle both built-in and custom exceptions in a unified manner.\n",
    "\n",
    "4 Standard Exception Features: The Exception class often provides various features and methods that are useful for handling exceptions. For example, it may include properties like an error message, a stack trace, and methods for retrieving or manipulating this information. By deriving from Exception, your custom exception can inherit these features, which can be beneficial for debugging and logging purposes.\n",
    "\n",
    "5 Compatibility with Language Constructs: Some language constructs or libraries specifically expect or work with exceptions derived from the base Exception class. For instance, when using try-catch blocks or when utilizing exception handling mechanisms provided by frameworks, they often assume exceptions to be of type Exception or its subclasses. By using the Exception class as the base for your custom exception, you ensure compatibility with such constructs and frameworks.\n",
    "\n",
    "Overall, using the Exception class as the base for custom exceptions provides consistency, code reuse, hierarchy-based handling, and compatibility with language features. It helps maintain best practices, facilitates understanding, and promotes a standardized approach to exception handling within the language ecosystem."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "776885ce-0376-47f8-9296-f8db5c497199",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "Answer 2:Here's a Python program that prints the Python Exception Hierarchy:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9ce623ab-0e14-4b5c-be6e-4c4bbf736965",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "  Exception\n",
      "    TypeError\n",
      "      FloatOperation\n",
      "      MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "      ModuleNotFoundError\n",
      "      ZipImportError\n",
      "    OSError\n",
      "      ConnectionError\n",
      "        BrokenPipeError\n",
      "        ConnectionAbortedError\n",
      "        ConnectionRefusedError\n",
      "        ConnectionResetError\n",
      "          RemoteDisconnected\n",
      "      BlockingIOError\n",
      "      ChildProcessError\n",
      "      FileExistsError\n",
      "      FileNotFoundError\n",
      "      IsADirectoryError\n",
      "      NotADirectoryError\n",
      "      InterruptedError\n",
      "        InterruptedSystemCall\n",
      "      PermissionError\n",
      "      ProcessLookupError\n",
      "      TimeoutError\n",
      "      UnsupportedOperation\n",
      "      itimer_error\n",
      "      herror\n",
      "      gaierror\n",
      "      SSLError\n",
      "        SSLCertVerificationError\n",
      "        SSLZeroReturnError\n",
      "        SSLWantWriteError\n",
      "        SSLWantReadError\n",
      "        SSLSyscallError\n",
      "        SSLEOFError\n",
      "      Error\n",
      "        SameFileError\n",
      "      SpecialFileError\n",
      "      ExecError\n",
      "      ReadError\n",
      "      URLError\n",
      "        HTTPError\n",
      "        ContentTooShortError\n",
      "      BadGzipFile\n",
      "    EOFError\n",
      "      IncompleteReadError\n",
      "    RuntimeError\n",
      "      RecursionError\n",
      "      NotImplementedError\n",
      "        ZMQVersionError\n",
      "        StdinNotImplementedError\n",
      "      _DeadlockError\n",
      "      BrokenBarrierError\n",
      "      BrokenExecutor\n",
      "        BrokenThreadPool\n",
      "      SendfileNotAvailableError\n",
      "      ExtractionError\n",
      "      VariableError\n",
      "    NameError\n",
      "      UnboundLocalError\n",
      "    AttributeError\n",
      "      FrozenInstanceError\n",
      "    SyntaxError\n",
      "      IndentationError\n",
      "        TabError\n",
      "    LookupError\n",
      "      IndexError\n",
      "      KeyError\n",
      "        NoSuchKernel\n",
      "        UnknownBackend\n",
      "      CodecRegistryError\n",
      "    ValueError\n",
      "      UnicodeError\n",
      "        UnicodeEncodeError\n",
      "        UnicodeDecodeError\n",
      "        UnicodeTranslateError\n",
      "      UnsupportedOperation\n",
      "      JSONDecodeError\n",
      "      SSLCertVerificationError\n",
      "      Error\n",
      "      UnsupportedDigestmodError\n",
      "      IllegalMonthError\n",
      "      IllegalWeekdayError\n",
      "      ParserError\n",
      "      ClassNotFound\n",
      "      ClipboardEmpty\n",
      "      MessageDefect\n",
      "        NoBoundaryInMultipartDefect\n",
      "        StartBoundaryNotFoundDefect\n",
      "        CloseBoundaryNotFoundDefect\n",
      "        FirstHeaderLineIsContinuationDefect\n",
      "        MisplacedEnvelopeHeaderDefect\n",
      "        MissingHeaderBodySeparatorDefect\n",
      "        MultipartInvariantViolationDefect\n",
      "        InvalidMultipartContentTransferEncodingDefect\n",
      "        UndecodableBytesDefect\n",
      "        InvalidBase64PaddingDefect\n",
      "        InvalidBase64CharactersDefect\n",
      "        InvalidBase64LengthDefect\n",
      "        HeaderDefect\n",
      "          InvalidHeaderDefect\n",
      "          HeaderMissingRequiredValue\n",
      "          NonPrintableDefect\n",
      "          ObsoleteHeaderDefect\n",
      "          NonASCIILocalPartDefect\n",
      "          InvalidDateDefect\n",
      "      MacroToEdit\n",
      "      InvalidFileException\n",
      "      UnequalIterablesError\n",
      "      InvalidVersion\n",
      "      _InvalidELFFileHeader\n",
      "      InvalidWheelFilename\n",
      "      InvalidSdistFilename\n",
      "      InvalidSpecifier\n",
      "      InvalidMarker\n",
      "      UndefinedComparison\n",
      "      UndefinedEnvironmentName\n",
      "      InvalidRequirement\n",
      "        RequirementParseError\n",
      "      InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "      FloatingPointError\n",
      "      OverflowError\n",
      "      ZeroDivisionError\n",
      "        DivisionByZero\n",
      "        DivisionUndefined\n",
      "      DecimalException\n",
      "        Clamped\n",
      "        Rounded\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Inexact\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Subnormal\n",
      "          Underflow\n",
      "        DivisionByZero\n",
      "        FloatOperation\n",
      "        InvalidOperation\n",
      "          ConversionSyntax\n",
      "          DivisionImpossible\n",
      "          DivisionUndefined\n",
      "          InvalidContext\n",
      "    SystemError\n",
      "      CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "      UserWarning\n",
      "        GetPassWarning\n",
      "        FormatterWarning\n",
      "      EncodingWarning\n",
      "      DeprecationWarning\n",
      "        ProvisionalWarning\n",
      "      PendingDeprecationWarning\n",
      "      SyntaxWarning\n",
      "      RuntimeWarning\n",
      "        ProactorSelectorThreadWarning\n",
      "        UnknownTimezoneWarning\n",
      "        PEP440Warning\n",
      "      FutureWarning\n",
      "        ProvisionalCompleterWarning\n",
      "      ImportWarning\n",
      "      UnicodeWarning\n",
      "      BytesWarning\n",
      "      ResourceWarning\n",
      "      DeprecatedTzFormatWarning\n",
      "      PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "      CalledProcessError\n",
      "      TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "      CancelledError\n",
      "      TimeoutError\n",
      "      InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "      ZMQError\n",
      "        ContextTerminated\n",
      "        Again\n",
      "        InterruptedSystemCall\n",
      "      ZMQBindError\n",
      "      NotDone\n",
      "    PickleError\n",
      "      PicklingError\n",
      "      UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "      ConfigLoaderError\n",
      "        ArgumentError\n",
      "      ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "      MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "      NoSectionError\n",
      "      DuplicateSectionError\n",
      "      DuplicateOptionError\n",
      "      NoOptionError\n",
      "      InterpolationError\n",
      "        InterpolationMissingOptionError\n",
      "        InterpolationSyntaxError\n",
      "        InterpolationDepthError\n",
      "      ParsingError\n",
      "        MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "      EOF\n",
      "      TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "      TryNext\n",
      "      UsageError\n",
      "      StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "      InvalidAliasError\n",
      "    Error\n",
      "      InterfaceError\n",
      "      DatabaseError\n",
      "        InternalError\n",
      "        OperationalError\n",
      "        ProgrammingError\n",
      "        IntegrityError\n",
      "        DataError\n",
      "        NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "      IndexSizeErr\n",
      "      DomstringSizeErr\n",
      "      HierarchyRequestErr\n",
      "      WrongDocumentErr\n",
      "      InvalidCharacterErr\n",
      "      NoDataAllowedErr\n",
      "      NoModificationAllowedErr\n",
      "      NotFoundErr\n",
      "      NotSupportedErr\n",
      "      InuseAttributeErr\n",
      "      InvalidStateErr\n",
      "      SyntaxErr\n",
      "      InvalidModificationErr\n",
      "      NamespaceErr\n",
      "      InvalidAccessErr\n",
      "      ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "      InternalError\n",
      "      WrongVersion\n",
      "      RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "      MessageParseError\n",
      "        HeaderParseError\n",
      "        BoundaryError\n",
      "      MultipartConversionError\n",
      "      CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "      NotConnected\n",
      "      InvalidURL\n",
      "      UnknownProtocol\n",
      "      UnknownTransferEncoding\n",
      "      UnimplementedFileMode\n",
      "      IncompleteRead\n",
      "      ImproperConnectionState\n",
      "        CannotSendRequest\n",
      "        CannotSendHeader\n",
      "        ResponseNotReady\n",
      "      BadStatusLine\n",
      "        RemoteDisconnected\n",
      "      LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "      NoSuchProcess\n",
      "        ZombieProcess\n",
      "      AccessDenied\n",
      "      TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "      ProtocolError\n",
      "      ResponseError\n",
      "      Fault\n",
      "    ParseBaseException\n",
      "      ParseException\n",
      "      ParseFatalException\n",
      "        ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "      VersionConflict\n",
      "        ContextualVersionConflict\n",
      "      DistributionNotFound\n",
      "      UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "  GeneratorExit\n",
      "  SystemExit\n",
      "  KeyboardInterrupt\n",
      "  CancelledError\n",
      "  AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, depth=0):\n",
    "    indent = '  ' * depth\n",
    "    print(indent + exception_class.__name__)\n",
    "    \n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, depth + 1)\n",
    "\n",
    "\n",
    "# Starting point of the program\n",
    "if __name__ == '__main__':\n",
    "    print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac797bfd-7c84-429a-9811-4c87bcc030de",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "da8b7e34-2aff-47af-9d09-20410bbf4ba8",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "Answer 3:The ArithmeticError class is a base class for arithmetic-related errors . It serves as a superclass for several specific arithmetic exception classes. Two examples of errors defined in the ArithmeticError class are FloatingPointError and ZeroDivisionError.\n",
    "\n",
    "1 FloatingPointError: This exception is raised when a floating-point operation fails to produce a valid result. It typically occurs when performing mathematical operations on floating-point numbers, such as division by zero or invalid calculations involving infinity or NaN (Not a Number).\n",
    "\n",
    "Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "a58103d3-50b7-4799-8674-43e46a085362",
   "metadata": {},
   "outputs": [
    {
     "ename": "FloatingPointError",
     "evalue": "invalid value encountered in sqrt",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFloatingPointError\u001b[0m                        Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[20], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mnumpy\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mnp\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m np\u001b[38;5;241m.\u001b[39merrstate(invalid\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraise\u001b[39m\u001b[38;5;124m'\u001b[39m):\n\u001b[0;32m----> 3\u001b[0m   \u001b[38;5;28mprint\u001b[39m(\u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msqrt\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m-\u001b[39;49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m)\u001b[49m)\n",
      "\u001b[0;31mFloatingPointError\u001b[0m: invalid value encountered in sqrt"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "with np.errstate(invalid='raise'):\n",
    "  print(np.sqrt(-1))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b7898889-6d1f-4839-9da6-c8834c4690b0",
   "metadata": {},
   "source": [
    "2.ZeroDivisionError: This exception is raised when an operation or function encounters division or modulo by zero.\n",
    "\n",
    "Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "ee186731-f9e2-4f44-aaf3-30c814de8f36",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ZeroDivisionError: division by zero\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"ZeroDivisionError:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cadb8c8b-e80a-4efc-8f4f-b8fb36df6327",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "40979676-5ec6-4d2f-bee5-1d8d3c40ee93",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "Answer4:The LookupError class is a base class for exceptions that occur when a lookup or indexing operation fails. It is a subclass of the built-in Exception class and provides a way to handle common lookup-related errors.\n",
    "\n",
    "The LookupError class is typically used as a catch-all for more specific lookup-related exceptions such as KeyError and IndexError. These exceptions occur when trying to access elements in a collection, such as a dictionary or a list, using incorrect or non-existent keys or indices.\n",
    "\n",
    "Let's take a closer look at KeyError and IndexError to understand how they relate to LookupError:\n",
    "\n",
    "1.KeyError: This exception is raised when trying to access a dictionary with a key that doesn't exist. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "8b8aeba6-ceac-4043-8c73-e66e7c15aa6c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Key not found in dictionary\n"
     ]
    }
   ],
   "source": [
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict['d']  # Accessing a non-existent key\n",
    "except KeyError:\n",
    "    print(\"Key not found in dictionary\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b9106806-d250-4fdb-a662-8b3b7b1c8dc7",
   "metadata": {},
   "source": [
    "2.IndexError: This exception is raised when trying to access a list or other sequence using an invalid index. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "bf3ef687-a932-4c8d-9e0c-0e222164a124",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index out of range\n"
     ]
    }
   ],
   "source": [
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[4]  # Accessing an index that is out of range\n",
    "except IndexError:\n",
    "    print(\"Index out of range\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5583b6f6-60ef-418f-99bc-6f4b6ce27f7f",
   "metadata": {},
   "source": [
    "Both KeyError and IndexError are subclasses of LookupError, which means that when you catch a LookupError exception, it will also catch these more specific exceptions. This allows you to handle them in a unified way if you want to perform the same actions for both types of lookup errors."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6fc4a930-78bf-48d8-9161-2f17c54564e7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "5bb2d66b-8c77-490d-8898-5ec2feb78bc4",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "Answer5:ImportError and ModuleNotFoundError are exceptions that can occur when importing modules or packages. Let's take a closer look at each of them:\n",
    "\n",
    "ImportError: This exception is raised when an import statement fails to import a module. It can occur due to various reasons, such as:\n",
    "\n",
    "The module or package you are trying to import does not exist.\n",
    "The module or package is not installed in your Python environment.\n",
    "There is an error within the module being imported (e.g., syntax error, missing dependencies).\n",
    "When an ImportError occurs, Python raises an exception and provides a traceback indicating the source of the problem. You can catch and handle this exception using a try-except block to perform alternative actions or display a custom error message.\n",
    "\n",
    "ModuleNotFoundError: Starting from Python 3.6, ModuleNotFoundError is a subclass of ImportError. It is specifically raised when a module or package cannot be found during the import process. This exception is a more specific version of ImportError and is raised when the module or package you are trying to import cannot be located in any of the directories listed in the Python module search path (sys.path).\n",
    "\n",
    "The ModuleNotFoundError exception includes the name of the missing module or package, making it easier to identify the problem. Similar to ImportError, you can catch and handle this exception using a try-except block.\n",
    "\n",
    "It's worth noting that in earlier versions of Python (before 3.6), the ModuleNotFoundError exception did not exist, and ImportError would be raised for both cases where the module is not found and for other import-related errors.\n",
    "\n",
    "In summary, ImportError is a general exception that can occur when importing modules, and ModuleNotFoundError is a specific subclass of ImportError that is raised when a module or package cannot be found during the import process."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a896693-eeb9-49f8-adc2-13979da43676",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "84dfb3c2-3a4c-4fd6-92fd-6293f51690be",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3b569657-cd84-460d-a643-a46d848eb84c",
   "metadata": {},
   "source": [
    "Answer6:Here are some best practices for exception handling in Python:\n",
    "\n",
    "1 Be specific with exception handling: Catch and handle exceptions at the appropriate level of granularity. Instead of using a broad except clause that captures all exceptions, try to catch specific exceptions that you expect and can handle effectively. This helps in better error diagnosis and avoids unintentionally hiding other types of exceptions.\n",
    "\n",
    "2 Use multiple except clauses: When handling different types of exceptions, use multiple except clauses to handle each exception separately. This allows you to provide specific handling logic for different exceptions and makes your code more readable.\n",
    "\n",
    "3 Avoid bare except clauses: Avoid using a bare except clause (i.e., without specifying any exception type) as it can catch unexpected exceptions and make it harder to debug issues. Always be explicit about the exceptions you want to handle.\n",
    "\n",
    "4 Use finally for cleanup: If you need to perform cleanup actions, such as closing files or releasing resources, use a finally block. The code in the finally block will be executed regardless of whether an exception occurred or not, ensuring proper cleanup.\n",
    "\n",
    "5 Handle exceptions gracefully: Handle exceptions in a way that provides meaningful feedback to users or logs helpful information for debugging purposes. Avoid simply printing error messages to the console without context. Use logging or display user-friendly error messages to guide users on how to resolve the issue.\n",
    "\n",
    "6 Avoid catching and ignoring exceptions: It's generally not recommended to catch exceptions without taking any action. Ignoring exceptions can hide potential issues and make it harder to diagnose problems. If you catch an exception, make sure to either handle it appropriately or re-raise it if necessary.\n",
    "\n",
    "7 Use context managers and the with statement: For resources that need to be managed, such as file operations, use context managers and the with statement. This ensures that resources are properly released, even in the event of an exception, without explicitly writing cleanup code.\n",
    "\n",
    "8 Log exceptions: Consider using a logging framework to log exceptions and relevant information. This helps in troubleshooting and understanding the cause of exceptions when they occur in production environments.\n",
    "\n",
    "Remember, the goal of exception handling is to make your code robust, maintainable, and easily debuggable. By following these best practices, you can improve the quality of your exception handling in Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bcce4fde-9bb0-4446-a864-677b096113db",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
